version: 2
project_name: owctl
builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  ldflags:
  - -s
  - -w
  - -X github.com/stannum-l/owctl/cmd.GoVersion={{ .Version }}
  - -X github.com/stannum-l/owctl/cmd.Date={{ .CommitDate }}
  - -X github.com/stannum-l/owctl/cmd.GitCommit={{ .Version }}
  - -X github.com/stannum-l/owctl/cmd.Version={{ .Version }}
  - -X github.com/stannum-l/owctl/cmd.OsType ={{ .Os }}
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
dockers:
- image_templates: ["ghcr.io/goreleaser/example:{{ .Version }}"]
  dockerfile: Dockerfile
  build_flag_templates:
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
changelog:
  skip: true
release:
  prerelease: auto
