version: 2
project_name: owctl
builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  ldflags:
  - -s
  - -w
  - -X github.com/stannum-l/owctl/cmd.GoVersion={{ .Version }}
  - -X github.com/stannum-l/owctl/cmd.Date={{ .CommitDate }}
  - -X github.com/stannum-l/owctl/cmd.GitCommit={{ .Version }}
  - -X github.com/stannum-l/owctl/cmd.Version={{ .Version }}
  - -X github.com/stannum-l/owctl/cmd.OsType ={{ .Os }}
  goos:
  - darwin
  goarch:
  - arm64
changelog:
  skip: true
release:
  prerelease: auto
